export default {
  'KAAN โชว์': 'INTRO-TO-KAAN',
  'โชว์คาน': 'INTRO-TO-KAAN',
  'show in Thailand': 'INTRO-TO-KAAN',
  'show in Pattaya': 'INTRO-TO-KAAN',
  'โชว์พัทยา': 'INTRO-TO-KAAN',
  'Fantasy Thailand': 'INTRO-TO-KAAN',
  'Attraction Thailand ': 'INTRO-TO-KAAN',
  'Attraction Pattaya': 'INTRO-TO-KAAN',
  'Best show in Thailand': 'INTRO-TO-KAAN',
  'Best show in Pattaya': 'INTRO-TO-KAAN',
  'เรื่อง KAAN': ['THE-STORY', 'WORLD-OF-KAAN'],
  'เนื้อเรื่อง KAAN': ['THE-STORY', 'WORLD-OF-KAAN'],
  'เรื่องย่อ KAAN': ['THE-STORY', 'WORLD-OF-KAAN'],
  'KAAN Story': ['THE-STORY', 'WORLD-OF-KAAN'],
  'KAAN Script': ['THE-STORY', 'WORLD-OF-KAAN'],
  'แรงบันดาลใจ KAAN': 'THE-STORY',
  'วรรณคดีไทย KAAN': ['THE-STORY', 'WORLD-OF-KAAN'],
  'ที่ไปที่มา KAAN': 'THE-STORY',
  'เนื้อหา KAAN': 'THE-STORY',
  'เรื่อง KAAN โชว์': 'THE-STORY',
  'รูป KAAN': 'GALLERY',
  'KAAN Gallery': 'GALLERY',
  'KAAN Album ': 'GALLERY',
  'KAAN Picture': 'GALLERY',
  'KAAN Photo': 'GALLERY',
  'รูปการแสดง KAAN': 'GALLERY',
  'รูปโชว์ KAAN': 'GALLERY',
  'อัลบัมรูป KAAN': 'GALLERY',
  'KAAN Character': 'GALLERY',
  'ตัวละคร KAAN': 'GALLERY',
  'เบื้องหลัง KAAN': 'MAKING-THE-SHOW',
  'Behind the scene KAAN': 'MAKING-THE-SHOW',
  'KAAN VDO': 'MAKING-THE-SHOW',
  'KAAN Clip': 'MAKING-THE-SHOW',
  'KAAN YouTube': 'MAKING-THE-SHOW',
  'Making of KAAN': 'MAKING-THE-SHOW',
  'KAAN Production': 'MAKING-THE-SHOW',
  'KAAN Design ': 'MAKING-THE-SHOW',
  'D’LUCK': 'ABOUT-DLUCK',
  'โรงละครดีลักษณ์': 'ABOUT-DLUCK',
  'ดีลักษณ์ พัทยา': ['ABOUT-DLUCK', 'GALLERY'],
  'Cinematic Theatre': 'ABOUT-DLUCK',
  'โรงละครลอยได้': 'ABOUT-DLUCK',
  'Levitating Theatre ': 'ABOUT-DLUCK',
  'KAAN Theatre': 'ABOUT-DLUCK',
  'KAAN Venue': 'ABOUT-DLUCK',
  'สถานที่แสดง KAAN': 'ABOUT-DLUCK',
  'โรงละคร พัทยา': 'ABOUT-DLUCK',
  'รูปโรงละครดีลักษณ์': 'GALLERY',
  'รูป D’LUCK': 'GALLERY',
  'D’LUCK Gallery': 'GALLERY',
  'D’LCUK Album ': 'GALLERY',
  'D’LUCK Picture': 'GALLERY',
  'D’LUCK Photo': 'GALLERY',
  'D’LUCK Perspective': 'GALLERY',
  'D’LUCK Design': 'GALLERY',
  'Levitating Theatre': 'GALLERY',
  'ที่นั่ง KAAN': 'SEATING-PLAN',
  'ผังที่นั่ง KAAN': 'SEATING-PLAN',
  'Seating Plan KAAN': 'SEATING-PLAN',
  'KAAN Seating': 'SEATING-PLAN',
  'KAAN Booking': 'SEATING-PLAN',
  'KAAN Ticketing': 'SEATING-PLAN',
  'ที่นั่งที่ดีที่สุด KAAN': 'SEATING-PLAN',
  'หาที่นั่ง KAAN': 'SEATING-PLAN',
  'Best Seat KAAN': 'SEATING-PLAN',
  'ที่ตั้ง KAAN': 'LOCATION-MAP',
  'ที่ตั้ง D’LUCK': 'LOCATION-MAP',
  'KAAN Location': 'LOCATION-MAP',
  'D’LUCK Location': 'LOCATION-MAP',
  'KAAN Map': 'LOCATION-MAP',
  'D’LUCK Map': 'LOCATION-MAP',
  'KAAN อยู่ตรงไหน': 'LOCATION-MAP',
  'D’LUCK อยู่ตรงไหน': 'LOCATION-MAP',
  'แผนที่ D’LUCK': 'LOCATION-MAP',
  'แผนที่ KAAN ': 'LOCATION-MAP',
  'KAAN Street View': 'THEATRE-360',
  'D’LUCK Street View': 'THEATRE-360',
  'KAAN 360': 'THEATRE-360',
  'D’LUCK 360': 'THEATRE-360',
  'ดูภาพจริง KAAN': 'THEATRE-360',
  'ดูภายในโรงละคร KAAN': 'THEATRE-360',
  'ดูภายใน D’LUCK': 'THEATRE-360',
  'ภาพ 360 องศา D’LUCK': 'THEATRE-360',
  'สำรวจโรงละคร D’LUCK': 'THEATRE-360',
  'สำรวจ KAAN': 'THEATRE-360',
  'สิ่งอำนวยความสะดวก D’LUCK': 'FACILITIES',
  'D’LUCK Facility': 'FACILITIES',
  'ร้านอาหาร': 'FACILITIES',
  'ที่ขายตั๋ว': 'FACILITIES',
  'Ticket Center': 'FACILITIES',
  'ที่จอดรถ': 'FACILITIES',
  'ร้านขายของที่ระลึก': 'FACILITIES',
  'Souvenir Shop': 'FACILITIES',
  'ประชาสัมพันธ์': 'FACILITIES',
  'Food and Drink': 'FACILITIES',
  'ปัญจลักษณ์': 'OUR-BUSINESS',
  'Panjaluck': 'OUR-BUSINESS',
  'ประวัติปัญจลักษณ์': 'OUR-BUSINESS',
  'Panjaluck history': 'OUR-BUSINESS',
  'ประวัติ KAAN': 'OUR-BUSINESS',
  'KAAN history': 'OUR-BUSINESS',
  'ก่อตั้งปัญจลักษณ์': 'OUR-BUSINESS',
  'Panjaluck founder ': 'OUR-BUSINESS',
  'ก่อตั้ง KAAN': 'OUR-BUSINESS',
  'KAAN founder ': 'OUR-BUSINESS',
  'Panjaluck Vision': 'VISION',
  'วิสัยทัศน์องค์กร ปัญจลักษณ์': 'VISION',
  'KAAN Vision': 'VISION',
  'วิสัยทัศน์องค์กร KAAN': 'VISION',
  'Panjaluck Mission': 'VISION',
  'พันธกิจองค์กร ปัญจลักษณ์': 'VISION',
  'Panjaluck Business': 'VISION',
  'Corporate Panjaluck': 'CORPORATE',
  'Corporate Value Panjaluck': 'CORPORATE',
  'ค่านิยมองค์กร ปัญจลักษณ์': 'CORPORATE',
  'CHARM Panjaluck': 'CORPORATE',
  'Panjaluck indentity ': 'CORPORATE',
  'องค์กร ปัญจลักษณ์': 'CORPORATE',
  'ผู้บริหาร ปัญจลักษณ์': 'BOARD',
  'ผู้บริหาร KAAN': 'BOARD',
  'KAAN Committee ': 'BOARD',
  'KAAN Board': 'BOARD',
  'Panjaluck Board': 'BOARD',
  'Panjaluck management board ': 'BOARD',
  'ทีมบริหาร KAAN': 'BOARD',
  'กรรมการบริหาร ปัญจลักษณ์': 'BOARD',
  'กรรมการบริหาร KAAN ': 'BOARD',
  'KAAN CEO': 'BOARD',
  'KAAN Partner': 'partner-page',
  'KAAN Business Partner ': 'partner-page',
  'พันธมิตร KAAN': 'partner-page',
  'Panjaluck Business Partner': 'partner-page',
  'สนุกดีทวีสุข': 'partner-page',
  'Scenario': 'partner-page',
  'BAANRIG': 'partner-page',
  'xtreme plus ': 'partner-page',
  'A49': 'partner-page',
  'ฤทธา ': 'partner-page',
  'สมัครงาน KAAN': 'faq-page',
  'สมัครงานดีลักษณ์': 'faq-page',
  'สมัครงาน D’LUCK': 'faq-page',
  'KAAN Job': 'faq-page',
  'D’LUCK Job': 'faq-page',
  'หางานพัทยา': 'faq-page',
  'ตำแหน่งว่างพัทยา': 'faq-page',
  'รับสมัครงานพัทยา': 'faq-page',
  'Entertainment Job': 'faq-page',
  'Job Pattaya': 'faq-page',
  'KAAN Ticket': 'ticket',
  'ตั๋ว KAAN': 'ticket',
  'บัตร KAAN': 'ticket',
  'KAAN booking': 'ticket',
  'จองตั๋ว KAAN': ['ticket', 'SEATING-PLAN'],
  'KAAN ตั๋วราคาประหยัด ': 'ticket',
  'KAAN discount ticket ': 'ticket',
  'KAAN Promotion': 'ticket',
  'KAAN Sale': 'ticket',
  'Best price KAAN': 'ticket',
  'ข่าว KAAN': 'info/download',
  'KAAN News': 'info/download',
  'KAAN PR': 'info/download',
  'ข่าว PR KAAN': 'info/download',
  'KAAN Press Release': 'info/download',
  'KAAN Fact Sheet': 'info/download',
  'KAAN Information': 'info/download',
  'KAAN Press': 'info/download',
  'ข่าวประชาสัมพันธ์ KAAN': 'info/download',
  'D’LUCK News': 'info/download',
  'FAQ KAAN': 'info/faq',
  'ถามตอบ KAAN': 'info/faq',
  'Q&A KAAN': 'info/faq',
  'Contact KAAN': 'info/faq',
  'วิธีจองบัตร KAAN': 'info/faq',
  'วิธีรับตั๋ว KAAN': 'info/faq',
  'เปิดปิด KAAN': 'info/faq',
  'Wheelchair': 'info/faq',
  'คนพิการ': 'info/faq',
  'เด็ก': 'info/faq'
}
